//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonLife.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DungeonLife.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data&gt;
        ///  &lt;Events&gt;
        ///    &lt;ID&gt;1&lt;/ID&gt;
        ///    &lt;Event&gt;LosePet&lt;/Event&gt;
        ///    &lt;Weight&gt;10&lt;/Weight&gt;
        ///    &lt;Keyword&gt;Pet&lt;/Keyword&gt;
        ///    &lt;Actionkeys&gt;LoseHappy,LosePet&lt;/Actionkeys&gt;
        ///    &lt;Text&gt;Your pet has died.&lt;/Text&gt;
        ///  &lt;/Events&gt;
        ///  &lt;Events&gt;
        ///    &lt;ID&gt;2&lt;/ID&gt;
        ///    &lt;Event&gt;LoseSibling&lt;/Event&gt;
        ///    &lt;Weight&gt;10&lt;/Weight&gt;
        ///    &lt;Keyword&gt;Sibling&lt;/Keyword&gt;
        ///    &lt;Actionkeys&gt;LoseSibling&lt;/Actionkeys&gt;
        ///    &lt;Text&gt;Your Sibling has died.&lt;/Text&gt;
        ///  &lt;/Events&gt;
        ///&lt;/data&gt;
        ///.
        /// </summary>
        public static string EventsBad {
            get {
                return ResourceManager.GetString("EventsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data&gt;
        ///  &lt;Events&gt;
        ///    &lt;ID&gt;1&lt;/ID&gt;
        ///    &lt;Event&gt;GetPet&lt;/Event&gt;
        ///    &lt;Weight&gt;10&lt;/Weight&gt;
        ///    &lt;Keyword&gt;Parents&lt;/Keyword&gt;
        ///    &lt;Actionkeys&gt;GainHappy,GainPet&lt;/Actionkeys&gt;
        ///    &lt;Text&gt;You&apos;re parents bought you a new pet.&lt;/Text&gt;
        ///  &lt;/Events&gt;
        ///  &lt;Events&gt;
        ///    &lt;ID&gt;2&lt;/ID&gt;
        ///    &lt;Event&gt;GetSibling&lt;/Event&gt;
        ///    &lt;Weight&gt;10&lt;/Weight&gt;
        ///    &lt;Keyword&gt;Parents&lt;/Keyword&gt;
        ///    &lt;Actionkeys&gt;GainSibling&lt;/Actionkeys&gt;
        ///    &lt;Text&gt;You&apos;re parents had a new baby.&lt;/Text&gt;
        ///  &lt;/Events&gt;
        ///&lt;/data&gt;
        ///
        ///.
        /// </summary>
        public static string EventsGood {
            get {
                return ResourceManager.GetString("EventsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Data&gt;
        ///  &lt;Male&gt;
        ///    &lt;Name&gt;Abel&lt;/Name&gt;
        ///    &lt;Name&gt;Austin&lt;/Name&gt;
        ///    &lt;Name&gt;Jared&lt;/Name&gt;
        ///    &lt;Name&gt;Yair&lt;/Name&gt;
        ///    &lt;Name&gt;Lincoln&lt;/Name&gt;
        ///    &lt;Name&gt;Trystan&lt;/Name&gt;
        ///    &lt;Name&gt;Rylan&lt;/Name&gt;
        ///    &lt;Name&gt;Gianni&lt;/Name&gt;
        ///    &lt;Name&gt;Aidyn&lt;/Name&gt;
        ///    &lt;Name&gt;Kyler&lt;/Name&gt;
        ///    &lt;Name&gt;Rocco&lt;/Name&gt;
        ///    &lt;Name&gt;Javier&lt;/Name&gt;
        ///    &lt;Name&gt;Max&lt;/Name&gt;
        ///    &lt;Name&gt;Dalton&lt;/Name&gt;
        ///    &lt;Name&gt;Phillip&lt;/Name&gt;
        ///    &lt;Name&gt;Carlos&lt;/Name&gt;
        ///    &lt;Name&gt;Gaige&lt;/Name&gt;
        ///    &lt;Name&gt;Nathanial&lt;/N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Occupations&gt;
        ///  &lt;Jobs&gt;
        ///    &lt;Occupation&gt;Unemployed&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Actor&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Advocate&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Alchemist&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Animal Handler&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Apothecary&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Archer&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Architect&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Archivist&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Aristocrat&lt;/Occupation&gt;
        ///    &lt;Occupation&gt;Armorer&lt;/Occupa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Occupations {
            get {
                return ResourceManager.GetString("Occupations", resourceCulture);
            }
        }
    }
}
